spring:
  profiles:
    active: secret
  application:
    name: Gathr

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: url
      port: 0

security:
  jwt:
    secret-key: secretKey
    expiration: time             # 1시간
    refresh-expiration: time   # 7일