spring:
  profiles:
    active: secret
  application:
    name: Gathr

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: url
      port: 0

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10분

cloud:
  aws:
    bucket: bucket
    stack:
      auto: false
    region:
      static: region
    credentials:
      accessKey: accessKey
      secretKey: secretKey

security:
  jwt:
    secret-key: secretKey
    expiration: time             # 1시간
    refresh-expiration: time   # 7일